apiVersion: v1
kind: Pod
metadata:
  name: fluentd
spec:
  containers:
    - name: fluentd
      image: fluent/fluentd:v1.16
      volumeMounts:
        - mountPath: /fluentd/log
          name: varlog
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
